"""Update User types to Float and add unique constraint to Refeicao

Revision ID: 43c185732a63
Revises: 
Create Date: 2025-11-20 16:08:36.336280

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "43c185732a63"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exercicios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(length=255), nullable=False),
        sa.Column("descricao", sa.Text(), nullable=True),
        sa.Column("tipo", sa.String(), nullable=True),
        sa.Column("nivel", sa.String(), nullable=True),
        sa.Column("video_url", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_exercicios_id"), "exercicios", ["id"], unique=False)
    op.create_index(op.f("ix_exercicios_nome"), "exercicios", ["nome"], unique=True)
    op.create_table(
        "rotinas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(), nullable=False),
        sa.Column("descricao", sa.Text(), nullable=True),
        sa.Column("usuario_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_rotinas_id"), "rotinas", ["id"], unique=False)
    op.create_index(op.f("ix_rotinas_nome"), "rotinas", ["nome"], unique=False)
    op.create_table(
        "usuarios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(), nullable=False),
        sa.Column("idade", sa.Integer(), nullable=True),
        sa.Column("altura", sa.Float(), nullable=True),
        sa.Column("peso", sa.Float(), nullable=True),
        sa.Column("local_treino", sa.String(), nullable=True),
        sa.Column("frequencia_semana", sa.String(), nullable=True),
        sa.Column("objetivo", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_usuarios_id"), "usuarios", ["id"], unique=False)
    op.create_index(op.f("ix_usuarios_nome"), "usuarios", ["nome"], unique=False)
    op.create_table(
        "dias_treino",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rotina_id", sa.Integer(), nullable=False),
        sa.Column("identificacao", sa.String(), nullable=False),
        sa.Column("foco_muscular", sa.String(), nullable=True),
        sa.Column("ordem", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["rotina_id"],
            ["rotinas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dias_treino_id"), "dias_treino", ["id"], unique=False)
    op.create_index(
        op.f("ix_dias_treino_rotina_id"), "dias_treino", ["rotina_id"], unique=False
    )
    op.create_table(
        "feedbacks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=False),
        sa.Column("exercicio_id", sa.Integer(), nullable=False),
        sa.Column("gostou", sa.Boolean(), nullable=False),
        sa.Column("comentario", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["exercicio_id"],
            ["exercicios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_feedbacks_id"), "feedbacks", ["id"], unique=False)
    op.create_table(
        "refeicoes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(length=255), nullable=False),
        sa.Column("custo_estimado", sa.String(), nullable=True),
        sa.Column("tipo", sa.String(), nullable=True),
        sa.Column("nivel", sa.String(), nullable=True),
        sa.Column("ingredientes", sa.JSON(), nullable=False),
        sa.Column("link_receita", sa.String(), nullable=True),
        sa.Column("explicacao", sa.Text(), nullable=True),
        sa.Column("rotina_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["rotina_id"],
            ["rotinas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_refeicoes_id"), "refeicoes", ["id"], unique=False)
    op.create_index(op.f("ix_refeicoes_nome"), "refeicoes", ["nome"], unique=True)
    op.create_table(
        "rotina_exercicios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dia_id", sa.Integer(), nullable=False),
        sa.Column("exercicio_id", sa.Integer(), nullable=True),
        sa.Column("nome", sa.String(), nullable=False),
        sa.Column("series", sa.String(), nullable=True),
        sa.Column("repeticoes", sa.String(), nullable=True),
        sa.Column("descanso_segundos", sa.Integer(), nullable=True),
        sa.Column("detalhes_execucao", sa.Text(), nullable=True),
        sa.Column("video_url", sa.String(), nullable=True),
        sa.Column("ordem", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["dia_id"],
            ["dias_treino.id"],
        ),
        sa.ForeignKeyConstraint(
            ["exercicio_id"],
            ["exercicios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rotina_exercicios_dia_id"),
        "rotina_exercicios",
        ["dia_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rotina_exercicios_id"), "rotina_exercicios", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rotina_exercicios_id"), table_name="rotina_exercicios")
    op.drop_index(op.f("ix_rotina_exercicios_dia_id"), table_name="rotina_exercicios")
    op.drop_table("rotina_exercicios")
    op.drop_index(op.f("ix_refeicoes_nome"), table_name="refeicoes")
    op.drop_index(op.f("ix_refeicoes_id"), table_name="refeicoes")
    op.drop_table("refeicoes")
    op.drop_index(op.f("ix_feedbacks_id"), table_name="feedbacks")
    op.drop_table("feedbacks")
    op.drop_index(op.f("ix_dias_treino_rotina_id"), table_name="dias_treino")
    op.drop_index(op.f("ix_dias_treino_id"), table_name="dias_treino")
    op.drop_table("dias_treino")
    op.drop_index(op.f("ix_usuarios_nome"), table_name="usuarios")
    op.drop_index(op.f("ix_usuarios_id"), table_name="usuarios")
    op.drop_table("usuarios")
    op.drop_index(op.f("ix_rotinas_nome"), table_name="rotinas")
    op.drop_index(op.f("ix_rotinas_id"), table_name="rotinas")
    op.drop_table("rotinas")
    op.drop_index(op.f("ix_exercicios_nome"), table_name="exercicios")
    op.drop_index(op.f("ix_exercicios_id"), table_name="exercicios")
    op.drop_table("exercicios")
    # ### end Alembic commands ###
