"""verify_schema_consistency

Revision ID: 49c16b327609
Revises: i1j2k3l4m5n6
Create Date: 2026-05-25 06:33:22.511671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# identificadores de revisão, usados pelo Alembic.
revision: str = '49c16b327609'
down_revision: Union[str, Sequence[str], None] = 'i1j2k3l4m5n6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Atualiza o esquema (upgrade)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_feedbacks_id', table_name='feedbacks')
    op.drop_index('ix_feedbacks_usuario_created', table_name='feedbacks')
    op.create_index(op.f('ix_aican_feedbacks_id'), 'feedbacks', ['id'], unique=False, schema='aican')
    op.drop_constraint('feedbacks_usuario_id_fkey', 'feedbacks', type_='foreignkey')
    op.create_foreign_key(None, 'feedbacks', 'usuarios', ['usuario_id'], ['id'], source_schema='aican', referent_schema='aican', ondelete='CASCADE')
    op.drop_constraint('plano_dias_plano_id_fkey', 'plano_dias', type_='foreignkey')
    op.create_foreign_key(None, 'plano_dias', 'planos', ['plano_id'], ['id'], source_schema='aican', referent_schema='aican')
    op.drop_constraint('plano_exercicios_dia_id_fkey', 'plano_exercicios', type_='foreignkey')
    op.create_foreign_key(None, 'plano_exercicios', 'plano_dias', ['dia_id'], ['id'], source_schema='aican', referent_schema='aican')
    op.drop_constraint('plano_refeicoes_plano_id_fkey', 'plano_refeicoes', type_='foreignkey')
    op.create_foreign_key(None, 'plano_refeicoes', 'planos', ['plano_id'], ['id'], source_schema='aican', referent_schema='aican')
    op.alter_column('planos', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.drop_index('ix_planos_status', table_name='planos')
    op.drop_index('ix_planos_usuario_created', table_name='planos')
    op.create_index(op.f('ix_aican_planos_status'), 'planos', ['status'], unique=False, schema='aican')
    op.create_index(op.f('ix_aican_planos_usuario_id'), 'planos', ['usuario_id'], unique=False, schema='aican')
    op.drop_constraint('fk_planos_usuario_id', 'planos', type_='foreignkey')
    op.create_foreign_key(None, 'planos', 'usuarios', ['usuario_id'], ['id'], source_schema='aican', referent_schema='aican', ondelete='CASCADE')
    op.drop_index('ix_refresh_tokens_expires_at', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_family_id', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_token_hash', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_user_id', table_name='refresh_tokens')
    op.drop_constraint('uq_refresh_tokens_token_hash', 'refresh_tokens', type_='unique')
    op.create_index(op.f('ix_aican_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False, schema='aican')
    op.create_index(op.f('ix_aican_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False, schema='aican')
    op.create_index(op.f('ix_aican_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False, schema='aican')
    op.create_index(op.f('ix_aican_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True, schema='aican')
    op.create_index(op.f('ix_aican_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False, schema='aican')
    op.drop_constraint('refresh_tokens_user_id_fkey', 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'usuarios', ['user_id'], ['id'], source_schema='aican', referent_schema='aican', ondelete='CASCADE')
    op.drop_index('ix_usuarios_email', table_name='usuarios')
    op.drop_index('ix_usuarios_id', table_name='usuarios')
    op.drop_index('ix_usuarios_nome', table_name='usuarios')
    op.drop_constraint('uq_usuarios_email', 'usuarios', type_='unique')
    op.drop_index('ix_aican_usuarios_email', table_name='usuarios')
    op.create_index(op.f('ix_aican_usuarios_email'), 'usuarios', ['email'], unique=True, schema='aican')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverte o esquema (downgrade)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aican_usuarios_email'), table_name='usuarios', schema='aican')
    op.create_index('ix_aican_usuarios_email', 'usuarios', ['email'], unique=False)
    op.create_unique_constraint('uq_usuarios_email', 'usuarios', ['email'])
    op.create_index('ix_usuarios_nome', 'usuarios', ['nome'], unique=False)
    op.create_index('ix_usuarios_id', 'usuarios', ['id'], unique=False)
    op.create_index('ix_usuarios_email', 'usuarios', ['email'], unique=False)
    op.drop_constraint(None, 'refresh_tokens', schema='aican', type_='foreignkey')
    op.create_foreign_key('refresh_tokens_user_id_fkey', 'refresh_tokens', 'usuarios', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_aican_refresh_tokens_user_id'), table_name='refresh_tokens', schema='aican')
    op.drop_index(op.f('ix_aican_refresh_tokens_token_hash'), table_name='refresh_tokens', schema='aican')
    op.drop_index(op.f('ix_aican_refresh_tokens_id'), table_name='refresh_tokens', schema='aican')
    op.drop_index(op.f('ix_aican_refresh_tokens_family_id'), table_name='refresh_tokens', schema='aican')
    op.drop_index(op.f('ix_aican_refresh_tokens_expires_at'), table_name='refresh_tokens', schema='aican')
    op.create_unique_constraint('uq_refresh_tokens_token_hash', 'refresh_tokens', ['token_hash'])
    op.create_index('ix_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_index('ix_refresh_tokens_token_hash', 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index('ix_refresh_tokens_family_id', 'refresh_tokens', ['family_id'], unique=False)
    op.create_index('ix_refresh_tokens_expires_at', 'refresh_tokens', ['expires_at'], unique=False)
    op.drop_constraint(None, 'planos', schema='aican', type_='foreignkey')
    op.create_foreign_key('fk_planos_usuario_id', 'planos', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_aican_planos_usuario_id'), table_name='planos', schema='aican')
    op.drop_index(op.f('ix_aican_planos_status'), table_name='planos', schema='aican')
    op.create_index('ix_planos_usuario_created', 'planos', ['usuario_id', 'created_at'], unique=False)
    op.create_index('ix_planos_status', 'planos', ['status'], unique=False)
    op.alter_column('planos', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(None, 'plano_refeicoes', schema='aican', type_='foreignkey')
    op.create_foreign_key('plano_refeicoes_plano_id_fkey', 'plano_refeicoes', 'planos', ['plano_id'], ['id'])
    op.drop_constraint(None, 'plano_exercicios', schema='aican', type_='foreignkey')
    op.create_foreign_key('plano_exercicios_dia_id_fkey', 'plano_exercicios', 'plano_dias', ['dia_id'], ['id'])
    op.drop_constraint(None, 'plano_dias', schema='aican', type_='foreignkey')
    op.create_foreign_key('plano_dias_plano_id_fkey', 'plano_dias', 'planos', ['plano_id'], ['id'])
    op.drop_constraint(None, 'feedbacks', schema='aican', type_='foreignkey')
    op.create_foreign_key('feedbacks_usuario_id_fkey', 'feedbacks', 'usuarios', ['usuario_id'], ['id'])
    op.drop_index(op.f('ix_aican_feedbacks_id'), table_name='feedbacks', schema='aican')
    op.create_index('ix_feedbacks_usuario_created', 'feedbacks', ['usuario_id', 'created_at'], unique=False)
    op.create_index('ix_feedbacks_id', 'feedbacks', ['id'], unique=False)
    # ### end Alembic commands ###
