"""Refactor schema to plans and catalog

Revision ID: a0747ea43014
Revises: c1508b234e8b
Create Date: 2025-11-26 20:02:29.154507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# identificadores de revisão, usados pelo Alembic.
revision: str = 'a0747ea43014'
down_revision: Union[str, Sequence[str], None] = 'c1508b234e8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Atualiza o esquema (upgrade)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogo_exercicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('grupo_muscular', sa.String(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='aican'
    )
    op.create_index(op.f('ix_aican_catalogo_exercicios_id'), 'catalogo_exercicios', ['id'], unique=False, schema='aican')
    op.create_index(op.f('ix_aican_catalogo_exercicios_nome'), 'catalogo_exercicios', ['nome'], unique=True, schema='aican')
    op.create_table('catalogo_refeicoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('custo_estimado', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('nivel', sa.String(), nullable=True),
    sa.Column('ingredientes', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('link_receita', sa.String(), nullable=True),
    sa.Column('explicacao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='aican'
    )
    op.create_index(op.f('ix_aican_catalogo_refeicoes_id'), 'catalogo_refeicoes', ['id'], unique=False, schema='aican')
    op.create_index(op.f('ix_aican_catalogo_refeicoes_nome'), 'catalogo_refeicoes', ['nome'], unique=True, schema='aican')
    op.create_table('planos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='aican'
    )
    op.create_index(op.f('ix_aican_planos_id'), 'planos', ['id'], unique=False, schema='aican')
    op.create_index(op.f('ix_aican_planos_nome'), 'planos', ['nome'], unique=False, schema='aican')
    op.create_table('plano_dias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plano_id', sa.Integer(), nullable=False),
    sa.Column('identificacao', sa.String(), nullable=False),
    sa.Column('foco_muscular', sa.String(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plano_id'], ['aican.planos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='aican'
    )
    op.create_index(op.f('ix_aican_plano_dias_id'), 'plano_dias', ['id'], unique=False, schema='aican')
    op.create_index(op.f('ix_aican_plano_dias_plano_id'), 'plano_dias', ['plano_id'], unique=False, schema='aican')
    op.create_table('plano_refeicoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plano_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('custo_estimado', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('nivel', sa.String(), nullable=True),
    sa.Column('ingredientes', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('link_receita', sa.String(), nullable=True),
    sa.Column('explicacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plano_id'], ['aican.planos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='aican'
    )
    op.create_index(op.f('ix_aican_plano_refeicoes_id'), 'plano_refeicoes', ['id'], unique=False, schema='aican')
    op.create_index(op.f('ix_aican_plano_refeicoes_nome'), 'plano_refeicoes', ['nome'], unique=False, schema='aican')
    op.create_index(op.f('ix_aican_plano_refeicoes_plano_id'), 'plano_refeicoes', ['plano_id'], unique=False, schema='aican')
    op.create_table('plano_exercicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dia_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('series', sa.String(), nullable=True),
    sa.Column('repeticoes', sa.String(), nullable=True),
    sa.Column('descanso_segundos', sa.Integer(), nullable=True),
    sa.Column('detalhes_execucao', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dia_id'], ['aican.plano_dias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='aican'
    )
    op.create_index(op.f('ix_aican_plano_exercicios_dia_id'), 'plano_exercicios', ['dia_id'], unique=False, schema='aican')
    op.create_index(op.f('ix_aican_plano_exercicios_id'), 'plano_exercicios', ['id'], unique=False, schema='aican')
    # op.drop_index('ix_rotinas_id', table_name='rotinas')
    # op.drop_index('ix_rotinas_nome', table_name='rotinas')
    # op.drop_table('rotinas')
    # op.drop_index('ix_dias_treino_id', table_name='dias_treino')
    # op.drop_index('ix_dias_treino_rotina_id', table_name='dias_treino')
    # op.drop_table('dias_treino')
    # op.drop_table('alembic_version')
    # op.drop_index('ix_rotinas_id', table_name='rotinas', schema='aican')
    # op.drop_index('ix_rotinas_nome', table_name='rotinas', schema='aican')
    # op.drop_table('rotinas', schema='aican')
    # op.drop_index('ix_rotina_exercicios_dia_id', table_name='rotina_exercicios')
    # op.drop_index('ix_rotina_exercicios_id', table_name='rotina_exercicios')
    # op.drop_table('rotina_exercicios')
    # op.drop_index('ix_feedbacks_id', table_name='feedbacks')
    # op.drop_table('feedbacks')
    # op.drop_index('ix_dias_treino_id', table_name='dias_treino', schema='aican')
    # op.drop_index('ix_dias_treino_rotina_id', table_name='dias_treino', schema='aican')
    # op.drop_table('dias_treino', schema='aican')
    # op.drop_index('ix_rotina_exercicios_dia_id', table_name='rotina_exercicios', schema='aican')
    # op.drop_index('ix_rotina_exercicios_id', table_name='rotina_exercicios', schema='aican')
    # op.drop_table('rotina_exercicios', schema='aican')
    # op.drop_index('ix_usuarios_email', table_name='usuarios')
    # op.drop_index('ix_usuarios_id', table_name='usuarios')
    # op.drop_index('ix_usuarios_nome', table_name='usuarios')
    # op.drop_table('usuarios')
    # op.drop_index('ix_refeicoes_id', table_name='refeicoes')
    # op.drop_index('ix_refeicoes_nome', table_name='refeicoes')
    # op.drop_table('refeicoes')
    # op.drop_index('ix_exercicios_id', table_name='exercicios')
    # op.drop_index('ix_exercicios_nome', table_name='exercicios')
    # op.drop_table('exercicios')
    # op.drop_index('ix_refeicoes_id', table_name='refeicoes', schema='aican')
    # op.drop_index('ix_refeicoes_nome', table_name='refeicoes', schema='aican')
    # op.drop_table('refeicoes', schema='aican')
    # op.drop_index('ix_exercicios_id', table_name='exercicios', schema='aican')
    # op.drop_index('ix_exercicios_nome', table_name='exercicios', schema='aican')
    # op.drop_table('exercicios', schema='aican')
    # op.drop_index('ix_feedbacks_id', table_name='feedbacks', schema='aican')
    # op.create_index(op.f('ix_aican_feedbacks_id'), 'feedbacks', ['id'], unique=False, schema='aican')
    # op.drop_constraint('feedbacks_exercicio_id_fkey', 'feedbacks', schema='aican', type_='foreignkey')
    # op.create_foreign_key(None, 'feedbacks', 'catalogo_exercicios', ['exercicio_id'], ['id'], source_schema='aican', referent_schema='aican')
    # op.drop_index('ix_usuarios_email', table_name='usuarios', schema='aican')
    # op.drop_index('ix_usuarios_id', table_name='usuarios', schema='aican')
    # op.drop_index('ix_usuarios_nome', table_name='usuarios', schema='aican')
    op.create_index(op.f('ix_aican_usuarios_email'), 'usuarios', ['email'], unique=False, schema='aican')
    op.create_index(op.f('ix_aican_usuarios_id'), 'usuarios', ['id'], unique=False, schema='aican')
    op.create_index(op.f('ix_aican_usuarios_nome'), 'usuarios', ['nome'], unique=False, schema='aican')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverte o esquema (downgrade)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aican_usuarios_nome'), table_name='usuarios', schema='aican')
    op.drop_index(op.f('ix_aican_usuarios_id'), table_name='usuarios', schema='aican')
    op.drop_index(op.f('ix_aican_usuarios_email'), table_name='usuarios', schema='aican')
    op.create_index('ix_usuarios_nome', 'usuarios', ['nome'], unique=False, schema='aican')
    op.create_index('ix_usuarios_id', 'usuarios', ['id'], unique=False, schema='aican')
    op.create_index('ix_usuarios_email', 'usuarios', ['email'], unique=False, schema='aican')
    op.drop_constraint(None, 'feedbacks', schema='aican', type_='foreignkey')
    op.create_foreign_key('feedbacks_exercicio_id_fkey', 'feedbacks', 'exercicios', ['exercicio_id'], ['id'], source_schema='aican', referent_schema='aican')
    op.drop_index(op.f('ix_aican_feedbacks_id'), table_name='feedbacks', schema='aican')
    op.create_index('ix_feedbacks_id', 'feedbacks', ['id'], unique=False, schema='aican')
    op.create_table('exercicios',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"aican".exercicios_id_seq\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nivel', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('video_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='exercicios_pkey'),
    schema='aican',
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_exercicios_nome', 'exercicios', ['nome'], unique=True, schema='aican')
    op.create_index('ix_exercicios_id', 'exercicios', ['id'], unique=False, schema='aican')
    op.create_table('refeicoes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('custo_estimado', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nivel', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ingredientes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('link_receita', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('explicacao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rotina_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['rotina_id'], ['aican.rotinas.id'], name='refeicoes_rotina_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='refeicoes_pkey'),
    schema='aican'
    )
    op.create_index('ix_refeicoes_nome', 'refeicoes', ['nome'], unique=False, schema='aican')
    op.create_index('ix_refeicoes_id', 'refeicoes', ['id'], unique=False, schema='aican')
    op.create_table('exercicios',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('exercicios_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nivel', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('video_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='exercicios_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_exercicios_nome', 'exercicios', ['nome'], unique=True)
    op.create_index('ix_exercicios_id', 'exercicios', ['id'], unique=False)
    op.create_table('refeicoes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('custo_estimado', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nivel', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ingredientes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('link_receita', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('explicacao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rotina_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['rotina_id'], ['rotinas.id'], name='refeicoes_rotina_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='refeicoes_pkey')
    )
    op.create_index('ix_refeicoes_nome', 'refeicoes', ['nome'], unique=False)
    op.create_index('ix_refeicoes_id', 'refeicoes', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('usuarios_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('idade', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('altura', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('peso', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('local_treino', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('frequencia_semana', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('objetivo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hash_senha', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='usuarios_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_usuarios_nome', 'usuarios', ['nome'], unique=False)
    op.create_index('ix_usuarios_id', 'usuarios', ['id'], unique=False)
    op.create_index('ix_usuarios_email', 'usuarios', ['email'], unique=False)
    op.create_table('rotina_exercicios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dia_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exercicio_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('series', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('repeticoes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('descanso_segundos', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('detalhes_execucao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('video_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ordem', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dia_id'], ['aican.dias_treino.id'], name='rotina_exercicios_dia_id_fkey'),
    sa.ForeignKeyConstraint(['exercicio_id'], ['aican.exercicios.id'], name='rotina_exercicios_exercicio_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='rotina_exercicios_pkey'),
    schema='aican'
    )
    op.create_index('ix_rotina_exercicios_id', 'rotina_exercicios', ['id'], unique=False, schema='aican')
    op.create_index('ix_rotina_exercicios_dia_id', 'rotina_exercicios', ['dia_id'], unique=False, schema='aican')
    op.create_table('dias_treino',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rotina_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('identificacao', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('foco_muscular', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ordem', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['rotina_id'], ['aican.rotinas.id'], name='dias_treino_rotina_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='dias_treino_pkey'),
    schema='aican'
    )
    op.create_index('ix_dias_treino_rotina_id', 'dias_treino', ['rotina_id'], unique=False, schema='aican')
    op.create_index('ix_dias_treino_id', 'dias_treino', ['id'], unique=False, schema='aican')
    op.create_table('feedbacks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exercicio_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gostou', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('comentario', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['exercicio_id'], ['exercicios.id'], name='feedbacks_exercicio_id_fkey'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name='feedbacks_usuario_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='feedbacks_pkey')
    )
    op.create_index('ix_feedbacks_id', 'feedbacks', ['id'], unique=False)
    op.create_table('rotina_exercicios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dia_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exercicio_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('series', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('repeticoes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('descanso_segundos', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('detalhes_execucao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('video_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ordem', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dia_id'], ['dias_treino.id'], name='rotina_exercicios_dia_id_fkey'),
    sa.ForeignKeyConstraint(['exercicio_id'], ['exercicios.id'], name='rotina_exercicios_exercicio_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='rotina_exercicios_pkey')
    )
    op.create_index('ix_rotina_exercicios_id', 'rotina_exercicios', ['id'], unique=False)
    op.create_index('ix_rotina_exercicios_dia_id', 'rotina_exercicios', ['dia_id'], unique=False)
    op.create_table('rotinas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='rotinas_pkey'),
    schema='aican'
    )
    op.create_index('ix_rotinas_nome', 'rotinas', ['nome'], unique=False, schema='aican')
    op.create_index('ix_rotinas_id', 'rotinas', ['id'], unique=False, schema='aican')
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='alembic_version_pkc')
    )
    op.create_table('dias_treino',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rotina_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('identificacao', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('foco_muscular', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ordem', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['rotina_id'], ['rotinas.id'], name='dias_treino_rotina_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='dias_treino_pkey')
    )
    op.create_index('ix_dias_treino_rotina_id', 'dias_treino', ['rotina_id'], unique=False)
    op.create_index('ix_dias_treino_id', 'dias_treino', ['id'], unique=False)
    op.create_table('rotinas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='rotinas_pkey')
    )
    op.create_index('ix_rotinas_nome', 'rotinas', ['nome'], unique=False)
    op.create_index('ix_rotinas_id', 'rotinas', ['id'], unique=False)
    op.drop_index(op.f('ix_aican_plano_exercicios_id'), table_name='plano_exercicios', schema='aican')
    op.drop_index(op.f('ix_aican_plano_exercicios_dia_id'), table_name='plano_exercicios', schema='aican')
    op.drop_table('plano_exercicios', schema='aican')
    op.drop_index(op.f('ix_aican_plano_refeicoes_plano_id'), table_name='plano_refeicoes', schema='aican')
    op.drop_index(op.f('ix_aican_plano_refeicoes_nome'), table_name='plano_refeicoes', schema='aican')
    op.drop_index(op.f('ix_aican_plano_refeicoes_id'), table_name='plano_refeicoes', schema='aican')
    op.drop_table('plano_refeicoes', schema='aican')
    op.drop_index(op.f('ix_aican_plano_dias_plano_id'), table_name='plano_dias', schema='aican')
    op.drop_index(op.f('ix_aican_plano_dias_id'), table_name='plano_dias', schema='aican')
    op.drop_table('plano_dias', schema='aican')
    op.drop_index(op.f('ix_aican_planos_nome'), table_name='planos', schema='aican')
    op.drop_index(op.f('ix_aican_planos_id'), table_name='planos', schema='aican')
    op.drop_table('planos', schema='aican')
    op.drop_index(op.f('ix_aican_catalogo_refeicoes_nome'), table_name='catalogo_refeicoes', schema='aican')
    op.drop_index(op.f('ix_aican_catalogo_refeicoes_id'), table_name='catalogo_refeicoes', schema='aican')
    op.drop_table('catalogo_refeicoes', schema='aican')
    op.drop_index(op.f('ix_aican_catalogo_exercicios_nome'), table_name='catalogo_exercicios', schema='aican')
    op.drop_index(op.f('ix_aican_catalogo_exercicios_id'), table_name='catalogo_exercicios', schema='aican')
    op.drop_table('catalogo_exercicios', schema='aican')
    # ### end Alembic commands ###
