"""Add auth fields to user

Revision ID: c1508b234e8b
Revises: 43c185732a63
Create Date: 2025-11-26 18:48:04.357571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# identificadores de revisão, usados pelo Alembic.
revision: str = 'c1508b234e8b'
down_revision: Union[str, Sequence[str], None] = '43c185732a63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Atualiza o esquema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('email', sa.String(), nullable=False))
    op.add_column('usuarios', sa.Column('hash_senha', sa.String(), nullable=False))
    op.add_column('usuarios', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverte o esquema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_column('usuarios', 'is_active')
    op.drop_column('usuarios', 'hash_senha')
    op.drop_column('usuarios', 'email')
    # ### end Alembic commands ###
